# Generated by Django 5.2 on 2025-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
    ]
